### ISSUE TITLE
Review open issues

### ISSUE THREAD

**Issue by lxbarth** [osmlab/nycbuildings#88]
I've done a full review of all open issues and categorized them. I'd love to take this as a basis for a Google Hangout with all involved to agree on next steps.

@emacsen @ebarry @ebrelsford @ingalls @pnorman @iandees - please fill in your availability on this Doodle (this meeting is open, everyone else welcome to join in):

http://doodle.com/xvbbttpu9cfrddsu

The goal for the meeting is to walk through issues and agree on a way forward on them.
### A Fix in conversion + existing data

These are items that need a fix in the conversion code and in existing data. Of all issues discovered, the biggest one in here are buildings with height 0 and removing padding (first three). The rest is fairly straightforward.
- [x] Buildings with height=0.0 https://github.com/osmlab/nycbuildings/issues/61
- [x] Triangular buildings with no height? https://github.com/osmlab/nycbuildings/issues/57
- [x] Remove existing 0 padding on Queens addresses down to pad-2 https://github.com/osmlab/nycbuildings/issues/85
- [x] FDR Drive spelled differently than street https://github.com/osmlab/nycbuildings/issues/58
- [x] Fort Hamilton Parkway expansion https://github.com/osmlab/nycbuildings/issues/52
- [x] St Johns Place name expansion https://github.com/osmlab/nycbuildings/issues/45
- [x] Drop A and B addresses https://github.com/osmlab/nycbuildings/issues/116
### B Fix in existing data + document

These are items that need fix in existing data and documentation [in Common Issues doc](https://github.com/osmlab/nycbuildings/issues/86).
- [x] various addr:street vs tiger name mismatches https://github.com/osmlab/nycbuildings/issues/81
- [x] School buildings should be tagged building=school not amenity=school https://github.com/osmlab/nycbuildings/issues/47
- [x] Double address nodes https://github.com/osmlab/nycbuildings/issues/54
- [x] Duplicate Addresses on Fleet Street https://github.com/osmlab/nycbuildings/issues/75
- [x] Both, queens and non-queens addresses present https://github.com/osmlab/nycbuildings/issues/35
- [ ] Remove A and B addresses from existing data https://github.com/osmlab/nycbuildings/issues/117
### C Fix + document

These are all issues that need documentation, maybe a fix for the issue at hand but no fixes in existing data or conversion.
- [x] Situations unresolvable by the importer https://github.com/osmlab/nycbuildings/issues/73
- [x] Conflict resolution not clear (on where to split buildings) https://github.com/osmlab/nycbuildings/issues/74
- [x] Unhelpful changeset comments https://github.com/osmlab/nycbuildings/issues/65
- [x] Move POI nodes to their buildings if possible https://github.com/osmlab/nycbuildings/issues/59
- [x] Missed POI merges https://github.com/osmlab/nycbuildings/issues/48
- [x] Use English changeset comments https://github.com/osmlab/nycbuildings/issues/46
- [x] Odd building overlaps https://github.com/osmlab/nycbuildings/issues/38
- [x] Bad (or just suspicious) building geometry https://github.com/osmlab/nycbuildings/issues/62
- [x] Darnell Lane/Robin Court mismatch of TIGER and NYC address data https://github.com/osmlab/nycbuildings/issues/53
- [x] Add missing roads (street referenced which is not currently in the map) https://github.com/osmlab/nycbuildings/issues/82
- [x] Duplicate Addresses on Fleet Street https://github.com/osmlab/nycbuildings/issues/75
- [x] Some buildings near intersections have multiple address nodes very close together https://github.com/osmlab/nycbuildings/issues/43
- [x] Address nodes on garage https://github.com/osmlab/nycbuildings/issues/60
- [x] Buildings not split https://github.com/osmlab/nycbuildings/issues/78

_Moved to punt after January hangout_
- Duplexes are represented as two building polygons https://github.com/osmlab/nycbuildings/issues/50
- Strange holes in multipolygons https://github.com/osmlab/nycbuildings/issues/64
### D Punt

These are issues I suggest to punt on entirely.
- Duplicate magic BINs https://github.com/osmlab/nycbuildings/issues/69
- Missing addresses https://github.com/osmlab/nycbuildings/issues/66
- Gas Stations not buildings and not traced https://github.com/osmlab/nycbuildings/issues/63
- Building gone in imagery but exists in data https://github.com/osmlab/nycbuildings/issues/40
- Avenue of the Americas https://github.com/osmlab/nycbuildings/issues/34
- Extraneous Nodes https://github.com/osmlab/nycbuildings/issues/32
### E Address range issue

Address ranges are often but not always addresses that have been added for planning purposes. Based on the fact that most of these addresses are for planning purposes, I suggest we discard all range style addresses:
- [x] **Master ticket** - Keep house number ranges? https://github.com/osmlab/nycbuildings/issues/87

We discarded range style addresses, fixing the problems reported in these issues:
- Dashes in addresses https://github.com/osmlab/nycbuildings/issues/25
- Nodes with address ranges https://github.com/osmlab/nycbuildings/issues/55
- Range + single address nodes in building https://github.com/osmlab/nycbuildings/issues/70
- Infrequent duplicate address nodes https://github.com/osmlab/nycbuildings/issues/39
- Addresses duplicated w/ A/B ranges https://github.com/osmlab/nycbuildings/issues/71
- Single building with three address ranges https://github.com/osmlab/nycbuildings/issues/51
